"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname=usePathname()
  const route=['/login','/register']
  return (
    <html lang="en">
      <body className={inter.className}>
        {!route.includes(pathname) ?(<h1>Header</h1>):''}
 
        {children}
        {!route.includes(pathname) ?(<h1>Footer</h1>):''}
        </body>
    </html>
  );
}
